compile:
	@g++ blinker_oscillator.cpp -o blinker_oscillator
	@g++ toad_oscillator.cpp    -o toad_oscillator
	@g++ beacon_oscillator.cpp  -o beacon_oscillator

	@g++ randomized_board.cpp   -o randomized_board